pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

pypro/modulos/urls.py
from django.urls import path
from pypro.modulos import views


app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('', views.indice, name='indice'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
]

pypro/turmas/urls.py
from django.urls import path
from pypro.turmas import views


app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey(Modulo, on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'  #subescrever a ordem
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

pypro/turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video

def indice(requests):
    videos = Video.objects.order_by('creation').all()
    return render(requests, 'aperitivos/indice.html', context={'videos': videos})

def video(requests, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(requests, 'aperitivos/video.html', context=dict(video=video))

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade

def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)

def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})

pypro/turmas/views.py
from django.shortcuts import render


def indice(request):
    return render(request, 'turmas/indice.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivos{% endblock title %}
{% block description %}Página com todos vídeos gratuitos{% endblock description %}
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
            <h1 class="mt-4 mb-3">Lista de Vídeos Aperitivos</h1>
			<ol>
				{% for video in videos %}
					<li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título" }}</a></li>
				{% empty %}
					<li>Não foi encontrado nenhum vídeo de aperitivo</li>
				{% endfor %}
			</ol>
		</div>
	</div>
</div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página com vídeo gratuito de Python{% endblock description %}
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Título" }}</h1>
            <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
		</div>
	</div>
</div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title> {% block title %}Python Pro{% endblock title %} </title>

	<meta name="description" content=" {% block description %}Página do curso Python Pro {% endblock description %}">
	<meta name="author" content="André Marcos Gelhen">

	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Módulos
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					{% for modulo in MODULOS %}
						<a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a>
						<div class="dropdown-divider"></div>
					{% endfor %}
				</div>
			</li>
		</ul>
		{% if user.is_authenticated %}
			<ul class="navbar-nav">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						{{ user.first_name }}
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<div>
							<a class="btn btn-danger"	href="{% url 'logout' %}">Sair</a>
						</div>
					</div>
				</li>
			</ul>
		{% else %}
			<a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
		{% endif %}
	</div>
</nav>
{% block body %} {% endblock body %}

{% include 'base/footer.html' with contato_email='ramalho@python.com.br' only %}
</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Entre em Contato</h3>
				<address>
					+55 12 997-411-854
					<br/>
					<a href="mailto:{{ contato_email }}" class="text-light">{{ contato_email }}</a>
				</address>
			</div>
		</div>
	</div>
	<div class="rigths pb-4">
		<div class="container">
			<div class="row">
				<div class="col">
					{% now 'Y' %} Python Pro. Todos os direitos reservados.
				</div>
			</div>
		</div>
	</div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}

{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">

			<div class="jumbotron">
				<h2>
					Curso de Python com Luciano Ramalho
				</h2>
				<h4 class="mt-4">Matrículas abertas! Custo R$ 1000,00</h4>
				<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
				<form action="https://pagseguro.uol.com.br/checkout/v2/payment.html" method="post"
					  onsubmit="PagSeguroLightbox(this); return false;">
					<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
					<input type="hidden" name="code" value="7A04378D0101CC1224B6DF84017C792B"/>
					<input type="hidden" name="iot" value="button"/>
					<input type="image"
						   src="https://stc.pagseguro.uol.com.br/public/img/botoes/pagamentos/120x53-comprar.gif"
						   name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!"/>
				</form>
				<script type="text/javascript"
						src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script>
				<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->

				<!--				<h4 class="mt-4">Entre na fila de espera</h4>-->
				<!--				<form action="https://gmail.us20.list-manage.com/subscribe/post?u=7229ecf876877ad91e449cc33&amp;id=bdd988db5e"-->
				<!--					  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"-->
				<!--					  class="form-row align-items-center" target="_blank" novalidate>-->
				<!--					<div class="form-row align-items-center">-->
				<!--						<div class="col-auto">-->
				<!--							<label class="sr-only" for="mce-EMAIL">E-mail</label>-->
				<!--							<input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL" placeholder="exemplo@email.com">-->
				<!--						</div>-->
				<!--						<div class="col-auto">-->
				<!--							<label class="sr-only" for="mce-FNAME">E-mail</label>-->
				<!--							<input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Seu Nome">-->
				<!--						</div>-->

				<!--						&lt;!&ndash; real people should not fill this in and expect good things - do not remove this or risk form bot signups&ndash;&gt;-->
				<!--							<div style="position: absolute; left: -5000px;" aria-hidden="true">-->
				<!--								<input type="text" name="b_7229ecf876877ad91e449cc33_bdd988db5e" tabindex="-1" value="">-->
				<!--							</div>-->

				<!--						<div class="col-auto">-->
				<!--							<input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">-->
				<!--						</div>-->
				<!--					</div>-->
				<!--				</form>-->
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre o instrutor.
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="{% static 'img/luciano-ramalho.png' %}" alt="Foto de Luciano Ramalho" class="img-thumbnail float-left mr-3">
								Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e autor do
								Livro<a href="http://shop.oreilly.com/product/0636920032519.do" target="_blank">Python Fluente</a>.
								Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web.
								Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e outros, usando Python desde 1998.
								Como instrutor, atendeu clientes como Citibank, CPqD, Serpro, Presidência da República,
								Globo.com e Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou a
								criar a Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e
								fundador do Garoa Hacker Clube, o primeiro hackerspace do Brasil.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body %}

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página com vídeo gratuito de Python{% endblock description %}
{% block body %}
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="#">Home</a></li>
		<li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
		<li class="breadcrumb-item active" aria-current="page">{{ aula.titulo }}</li>
	  </ol>
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="mt-4 mb-3">{{ aula.titulo | default:"Faltando Título" }}</h1>
				<iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}" width="640" height="360" frameborder="0"
						allow="autoplay; fullscreen" allowfullscreen></iframe>
			</div>
		</div>
	</div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}
<div class="container">
	{% for modulo in modulos %}
		<div class="row">
			<div class="col-md-12">
				<h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
				<dl>
					<dt>Público</dt>
					<dd>{{ modulo.publico }}</dd>
					<dt>Descrição</dt>
					<dd>{{ modulo.descricao }}</dd>
				</dl>
				<h2>Aulas</h2>
				<ol>
					{% for aula in modulo.aulas %}
						<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
					{% endfor %}
				</ol>
			</div>
		</div>
	{% endfor %}
</div>
{% endblock body %}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
			<dl>
				<dt>Público</dt>
				<dd>{{ modulo.publico }}</dd>
				<dt>Descrição</dt>
				<dd>{{ modulo.descricao }}</dd>
			</dl>
			<h2>Aulas</h2>
			<ol>
				{% for aula in aulas %}
					<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
				{% endfor %}
			</ol>
		</div>
	</div>
</div>
{% endblock body %}

pypro/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Índice de Turmas{% endblock title %}
{% block description %}Página com todas as turmas do curso Python Pro{% endblock description %}
{% block body %}
<div class="container">
	<!--{% for modulo in modulos %}
		<div class="row">
			<div class="col-md-12">
				<h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
				<dl>
					<dt>Público</dt>
					<dd>{{ modulo.publico }}</dd>
					<dt>Descrição</dt>
					<dd>{{ modulo.descricao }}</dd>
				</dl>
				<h2>Aulas</h2>
				<ol>
					{% for aula in modulo.aulas %}
						<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
					{% endfor %}
				</ol>
			</div>
		</div>
	{% endfor %}-->
</div>
{% endblock body %}